### ISSUE TITLE
suggestion : Using data attributes

### ISSUE THREAD

**Issue by nabileisa** [jmarceli/integration-cmb2-qtranslate#1]
Hi , just found your Plugin and i find it very useful.
the only one issue i had with it and that was the use of class names  with non-WYSIWYG fields since it cause the removal of the default class names provided in CMB2 by default.
My suggestion is providing additional data attribute to be used with non-WYSIWYG fields to make it translatable than so it wont affect their default class names.
and thanks for your good work.

**Comment by jmarceli** [comment]
Thanks for the feedback. I didn't think that removing default CMB2 classes might be an issue. In the beginning I was planning to use the `data-attributes` but unfortunately WYSIWYG doesn't support it so I choose to use classes (which are "cross element").

In a few moments I will release version 0.0.3 which will support both classes and data attributes (for non-WYSIWYG fields).
