### ISSUE TITLE
Wysiwyg editor not working 

### ISSUE THREAD

**Issue by yeahsmaggy** [jmarceli/integration-cmb2-qtranslate#2]
When I add the class 'cmb2-qtranslate' to my wysiwyg field then the language switch buttons appear. I can switch the editor window and add different text, but it looks like when it comes to save, it is saving only one as after saving all language entries are the same. 

I have forked the plugin and I am looking to resolve the issue, but it would be good to hear if I have missed some step.

I commented out this bit and it works

```
 // remove all excessive translatable elements
 // wysiwygs are translatable by default
// (why? its probably some qTranslate default behaviour) 
 // it needs to be reset in case anyone doesn't want that
$meta_box.find('.qtranxs-translatable').each(function() {
   $(this).removeClass('qtranxs-translatable');
   qTranslateConfig.qtx.removeContentHook(this);
   });
```

**Comment by jmarceli** [comment]
Hi, I'll try to look into this tomorrow. I've just returned from short trip and I had a lot of work to do.

**Comment by jmarceli** [comment]
See the latest release. It should work fine now.

**Comment by yeahsmaggy** [comment]
Thanks for looking into it.
